package ctxkey

const (
	Config               = "config"
	Id                   = "id"
	Username             = "username"
	Role                 = "role"
	Status               = "status"
	Channel              = "channel"
	ChannelID            = "channel_id_str"
	ChannelId            = "channel_id"
	SpecificChannelId    = "specific_channel_id"
	RequestModel         = "request_model"
	OriginalRequestModel = "original_request_model"
	ConvertedRequest     = "converted_request"
	OriginalModel        = "original_model"
	Group                = "group"
	ModelMapping         = "model_mapping"
	ChannelName          = "channel_name"
	TokenId              = "token_id"
	TokenName            = "token_name"
	BaseURL              = "base_url"
	AvailableModels      = "available_models"
	KeyRequestBody       = "key_request_body"
	SystemPrompt         = "system_prompt"
	PlanId               = "plan_id"
	PlanLimits           = "plan_limits"
	BillingType          = "billing_type"
	DefaultModel         = "default_model"
	SessionKey           = "session_key"
	ConcurrencyAcquired  = "concurrency_acquired"
)
